### ISSUE TITLE
使用DOM元素初始化报错

### ISSUE THREAD

**Issue by Dr-Harris** [yaohaixiao/outline.js#35]
``` js
defaults.scrollElement = '#scroll'
defaults.articleElement = '#content'
```
正常展示，但是换成DOM元素

``` js
defaults.scrollElement = document.getElementById('scroll');
defaults.articleElement = document.getElementById('content');
```
报错：

```
outline.js:57  Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '[object HTMLDivElement]' is not a valid selector.
    at st.render (file:///D:/code/outline.js-master/docs/js/outline.min.js:1:34033)
    at st.initialize (file:///D:/code/outline.js-master/docs/js/outline.min.js:1:33860)
    at new st (file:///D:/code/outline.js-master/docs/js/outline.min.js:1:33768)
    at file:///D:/code/outline.js-master/docs/toc.html:153:15
```

**Comment by yaohaixiao** [comment]
不好意思，才看到，我会尽快处理的

**Comment by yaohaixiao** [comment]
问题已经修复，已可以验证一下，稍后我会关闭这个问题

**Comment by Dr-Harris** [comment]
已验证
